### ISSUE TITLE
Add `Throw.whenNaN(...)`

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/djutils-base#11]
A `Throw.whenNaN(...)` would be a good extension, since we have quite a number of places where we do want to check for `NaN` values as a precondition of a method. The method should take 4 types of values:
- `double`
- `float`
- `Double` with a check for `null`; when the value is `null`, no exception is thrown (the value is not `NaN`).
- `Float` with a check for `null`; when the value is `null`, no exception is thrown (the value is not `NaN`).

**Comment by averbraeck** [comment]
For now, we throw an `java.lang.ArithmeticException` when the tested value is NaN. `ArithmeticException` is a `RuntimeException`.

**Comment by averbraeck** [comment]
The code suffers from the weirdest error ever... Methods that are **ambiguous**, where the java standard specifies that always the most specific method is chosen. A small example:

```java
    public static void t(final double d, final String m, final Object o1, final Object... args) { }
    public static void t(final Double d, final String m, final Object o1, final Object... args) { }

    public static void main(final String... args)
    {
        t(2.0d, "x", "y", "z");
        t(Double.valueOf(1.0d), "x", "y", "z");
    }
```

This does **not** compile, neither in Java 11, nor in Java 17. 

The error is: `The method t(double, String, Object, Object[]) is ambiguous for the type Test`. Well, it is **NOT**.

**Comment by averbraeck** [comment]
For now, the problem has been solved by only including the varargs methods for `Double` and `Float`, and removing them for `double` and `float` arguments. These will be autoboxed to `Double` and `Float`.

**Comment by averbraeck** [comment]
Completed and working for now.

**Comment by WJSchakel** [comment]
The way I understand overload resolution from Java Language Specification (after looking it up) is that it works in three phases (see [JLS 15.12.2](https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.12.2)):
1. No (un)boxing, no varargs
2. No varargs
3. Everything allowed

Adding varargs forces phase 3, at which point the un(boxing) is already allowed and thus is unable to distinguish the methods.

A matter of choice, shall we say...

**Comment by WJSchakel** [comment]
So in phase 3 both methods are found, and specificity needs to select the most specific method. However, informally, as they can both call each other without error, they are equally specific. I.e. the following compiles.

```java
    public static void t1(final double d, final String m, final Object o1, final Object... args)
    {
        t2(d, m, o1, args);
    }

    public static void t2(final Double d, final String m, final Object o1, final Object... args)
    {
        t1(d, m, o1, args);
    }
```

**Comment by WJSchakel** [comment]
In phase 1 specificity (which would be equal) is not used, as only 1 method matches if (un)boxing is not allowed.
